### PR TITLE
Refactoring sep 2018

### PR DESCRIPTION
**Pull request by lmcmicu**
FYI I made the following changes in server.py that are worth noting, though note also that I verified that the output matches exactly to what it was prior to the refactoring work.

Changes in server.py:
=====================

- there seems to have been a bug in the way gates_errors was determined.

Special gates processing:
----
- no substitution of IRI url for 'PR:'

Exact synonyms processing:
----
- previously did not check to see if a label already existed in the short label map before inserting

General:
----
- labels are now converted to lower case when used as doctionary keys
- in the map from special labels to iri, the function stores a list of IRIs rather than a single one, so we need to flatten it.
- the old code checked against IRI and label for None.

### CODE REVIEW

**Comment by jamesaoverton** [comment]
This is good stuff. I'd like a few things clarified:

- docstrings for every function
- in `normalize.py` tests, `preferred` should be much closer to the reverse of `gate_mappings`, which will make it much easier to interpret failed tests

Also:

- `find-gates.py` should be removed; `report2.py` is an improved replacement

**Comment by lmcmicu** [comment]
> This is good stuff. I'd like a few things clarified:
> 
>     * docstrings for every function

Ok, I will do that for all outer functions. I'm not sure if it is possible to see docstrings on inner functions, though.

> 
>     * in `normalize.py` tests, `preferred` should be much closer to the reverse of `gate_mappings`, which will make it much easier to interpret failed tests

Ok.

> 
> 
> Also:
> 
>     * `find-gates.py` should be removed; `report2.py` is an improved replacement

Ok.

**Comment by lmcmicu** [comment]
Ok I have pushed those changes. Note that I didn't add docstrings to main() functions or to test functions or to inner functions. Let me know if this is ok, and also if you want more detail in the docstrings, etc.

Also, travis is failing and I am pretty sure this is because it is using `pytest` instead of `pytest-3`. Is there any way to reconfigure that?

Let me know when it is ok to merge. I'll do the actual merge, though, since there are conflicts.

**Comment by jamesaoverton** [comment]
I fixed Travis. Please fix the conflicts and I'll merge it. Thanks!

**Pull request merged**
